## Завдання на лабораторну работу №1

В цій лабораторної роботі Вам буде запропоновано вирішити кілька завдань скориставшись засобами мови python. Рішення кожного завдання передбачає написання коду і демонстрація його працездатності на прикладах. За кожне вірно виконане завдання Ви отримуєте **1 бал**.

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

[зверніть увагу на типізацію функцій](https://docs.python.org/3/library/typing.html)

```NB```: При написанні коду не забувайте видаляти ```pass```!

**Don't cheat!**

Перед тим, як надіслати своє завдання на перевірку, вкажіть в назві файлу своє ім'я та прізвище!
Наприклад: ```basic_ai_task1_python_ana_de.ipynb```

Завдання 1: На вхід функція приймає рядок s. Функція повинна повернути True якщо рядок є паліндромом та False – в протилежному випадку.

Наприклад: 

*   `is_palindrome(s='anade') -> False`
*   `is_palindrome(s='ana') -> True`




In [ ]:
def palindrome(x):
    x = x.replace(" ", "").lower()
    return x == x[::-1]

print(palindrome(x='anade'))
print(palindrome(x='ana'))  

Завдання 2: Розв’язати квадратне рівняння $ax^2+bx + c = 0$.  Напишіть функцію,яка приймає параметри квадратного рівняння, а повертає одне рішення або декілька.

Наприклад:  


```
solve_quad(a=1, b=-2, c=1) -> 1  
solve_quad(a=1, b=0, c=-1) -> (-1, 1)  
solve_quad(a=0, b=2, c=-1) -> 0.5
```





 

In [38]:
import math
def solve_quad(a: float, b: float, c: float):
    
    if a == 0:
        if b != 0:
            root = -c / b
            return root
        else:
            if c == 0:
                return "Багато коренів"
            else:
                return "Немає розв'язку"
  
    d = b ** 2 - 4 * a * c
  
    if d < 0:
        return None
    elif d == 0:
        root = -b / (2 * a)
        return root
    else:
        root1 = (-b - math.sqrt(d)) / (2 * a)
        root2 = (-b + math.sqrt(d)) / (2 * a)
        return root1, root2


print(solve_quad(a=1, b=-2, c=1))   # 1
print(solve_quad(a=1, b=0, c=-1))    # (-1, 1)
print(solve_quad(a=0, b=2, c=-1))    # 0.5


1.0
(-1.0, 1.0)
0.5


Завдання 3: Реалізація функції merge. На вхід функція приймає 2 відсортованих масиви - `a` і `b`. Функція повинна повернути один відсортований масив, який містить всі елементи масивів `a` і `b`. 

Наприклад: `merge([1, 3, 3, 5], [3, 5, 5, 7]) -> [1, 3, 3, 3, 5, 5, 5, 7]`

In [49]:
from typing import List

def merge(a: List[int], b: List[int]) -> List[int]:
    merged = []
    p = 0
    u = 0
 
    while p < len(a) and u < len(b):
        if a[p] <= b[u]:
            merged.append(a[p])
            p += 1
        else:
            merged.append(b[u])
            u += 1

    while p < len(a):
        merged.append(a[p])
        p += 1

    while u < len(b):
        merged.append(b[u])
        u += 1
    
    return merged

print(merge([1, 3, 3, 5], [3, 5, 5, 7]))


[1, 3, 3, 3, 5, 5, 5, 7]


Завдання 4: Реалізація алгоритму [MergeSort](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0_%D1%81%D0%BB%D0%B8%D1%8F%D0%BD%D0%B8%D0%B5%D0%BC)..

Наприклад: `MergeSort([3, 1, 3, 5]) -> [1, 3, 3, 5]`

In [51]:
from typing import List

def merge(left: List[int], right: List[int]) -> List[int]:
    merged = []
    p = u = 0

    while p < len(left) and u < len(right):
        if left[p] <= right[u]:
            merged.append(left[p])
            p += 1
        else:
            merged.append(right[u])
            u += 1

    merged.extend(left[p:])
    merged.extend(right[u:])
    return merged

def MergeSort(L: List[int]) -> List[int]:
    if len(L) <= 1:
        return L
    mid = len(L) // 2
    left_sorted = MergeSort(L[:mid])
    right_sorted = MergeSort(L[mid:])
    return merge(left_sorted, right_sorted)

print(MergeSort([3, 1, 3, 5]))
print(MergeSort([6, 2, 1, 8, 3, 3]))

[1, 3, 3, 5]
[1, 2, 3, 3, 6, 8]


## Знайомство з numpy.

Всі завдання з цієї частини передбачають написання функції на мові Python, а так само приклади роботи цієї функції. При реалізації завдань потрібно використовувати методи з бібліотеки `numpy`. Рішення з циклами будуть оцінені в 0 балів.

[базова документація](http://www.numpy.org)

```NB```: Під матрицею розуміється двовимірний [numpy.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

Для підключення модуля скористайтеся наступним рядком. 
Використовуйте стандартне скорочення np.

In [1]:
import numpy as np

Cтворення одномірного і двомірного масивів методами numpy:

In [2]:
Ar1d = np.array([1, 2, 3], dtype=np.float64)
print(Ar1d)

[1. 2. 3.]


In [3]:
Ar2d = np.array([[1, 2],
                [3, 4]], dtype=np.float64)
print(Ar2d)

[[1. 2.]
 [3. 4.]]


Завдання 6: Написати функцію яка на вхід приймає 3 масиви – `X, Y, Z`. функція повертатиме `True` у випадку, коли вони рівні та `False` – якщо ні.

Рекомендація до завдання: Не використовуйте оператор `==`

In [1]:
import numpy as np

def is_equal(X, Y, Z):
    return np.array_equal(X, Y) and np.array_equal(X, Z)

X = [1, 2, 3]
Y = [1, 2, 3]
Z = [1, 2, 3]
print(is_equal(X, Y, Z))

X = [3, 2, 3]
Y = [6, 5, 3]
Z = [3, 2, 3]
print(is_equal(X, Y, Z))


True
False


Завдання 7: написати функцію, яка приймає на вході вектор рядок, а повертає вектор стовбець.

Рекомендація до завдання: Забороняється використовувати операцію транспонування! Скористайтесь методом `reshape`.

In [17]:
import numpy as np

def rot_vec(x):
    return x.reshape(len(x), 1)

p = np.array([2, 2, 1, 4])
u = rot_vec(p)

print(u)


[[2]
 [2]
 [1]
 [4]]


Завдання 8: Написати функцію яка приймає на вхід двовимірний масив, а повертає масив з діагональними елементами цієї матриці. 

Наприклад: `[[1, 2], [3, 4]] -> [1 4]`

In [25]:
import numpy as np

def get_diag(x):
    return np.diag(x)

p = np.array([  [1, 2, 3],
                [4, 2, 6],
                [7, 1, 9],])

u = get_diag(p)
print(u)


[1 2 9]


Завдання 9: Написати функцію яка приймає на вхід двомірний масив, а повертає масив елементів які знаходяться на другорядній діагоналі. Приклад: `[[1, 2], [3, 4]] -> [2 3]`

In [29]:
import numpy as np

def sec_diag(x):
    flipped = np.fliplr(x)
    return np.diag(flipped)

p = np.array([  [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

u = sec_diag(p)
print(u)


[3 5 7]


## Робота з бібліотекою pandas

В наступній частині лабораторної роботи розглянемо бібліотеку pandas.
Перед виконанням цієї частини необхідно завантажити датасет `titanic.csv`

[основна документація цього розділу](https://pandas.pydata.org/)

In [ ]:
import pandas as pd

# Завантажте датасет. Ознайомтесь з тим як це правильно зробити, уважно прочитавши документацію по функції pd.read_csv.
# Зверніть особливу увагу на роздільники датасета. 

dataset = pd.read_csv(...)

Завдання 10: Кого більше - чоловіків чи жінок?

In [ ]:
#code

Завдання 11: Виведіть наступні характеристики пасажирів: середній вік пасажирів, середній вік чоловіків, середній вік жінок, максимальний і мінімальний вік серед чоловіків і жінок.

In [ ]:
#code

 ## Знайомство з бібліотекою matplotlib 

Для початку ознайомтесь з [документацією](https://matplotlib.org/)

Завдання 12: Побудувати задані функції: 

$f_{1}(x) =  \frac{sin(x)}{x}$

$f_{2}(x) =  \frac{cos(x)}{x^2 + 1}$

$f_{3}(x) =  cos^2(x) - \frac{sin(x)}{2}$  

$f_{4}(x) =  cos(x)$  

$f_{5}(x) =  \frac{sin(x)}{x^2 + 1}$

зробити візуалізацію заданих функцій  

In [ ]:
from matplotlib import pylab as plt
%matplotlib inline

In [ ]:
#code

In [ ]:
#code

Завдання 13: Побудувати графік щільності розподілу випадкової змінної.

зробити візуалізації

In [ ]:
#code

**Кожне завдання лабораторної роботи оцінюється в 1 бал (за умов правильного виконання)!!!!**

**Робота, яка ідентифікована як ПЛАГІАТ, буде оцінюватись в 0 балів!!!**

**Вибірково виконані завдання оцінюватись не будуть!!!**